簡単なシーケンス図の追加
ToyamaDataCenter/InventSample2024 pull request #6
Opened 2024-08-16 06:38 UTC by yohskeey

- github 上で見た場合に表示される簡単なシーケンス図を追加
  - 厳密には正確なシーケンス図ではないかもしれないが、理解のサポートができるかと
  - ローカル環境では`mermaid` をプレビューするための拡張機能が必要
    - Visual Studio Codeなら拡張機能あるけどVisual Studioにあるかどうか未確認 
- ブラウザ上では下のように見えます https://github.com/ToyamaDataCenter/InventSample2024/blob/62a03dcfd6f03e31c4663a9f153a2c6a989f2857/task/%E5%9C%A8%E5%BA%AB%E7%AE%A1%E7%90%86%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AE%E6%A6%82%E8%A6%81.md

2024-08-16 07:29 UTC, itou requested changes
- 何のシーケンス図なのか見出しを付けて欲しいです 
- 「入力在庫」へ追加 が何を指すのか、分かりにくいと感じました

2024-08-16 07:29 UTC, itou commented on task/在庫管理アプリの概要.md
> +```
`アプリ`オブジェクトの`「入力在庫」へ追加`手続きは、入力された値をオンメモリに持っているDataTableに書き込むことを指していますか？
パッと分かりませんでした。入力と登録は、何が違うのか、と思いました。

2024-08-16 07:29 UTC, itou commented on task/在庫管理アプリの概要.md
在庫登録のシーケンス図であることを示す見出しを付けて下さい

2024-08-16 07:29 UTC, itou commented on task/在庫管理アプリの概要.md
> +
在庫確認のシーケンス図であることを示す見出しを付けて下さい

2024-08-16 09:09 UTC, yohskeey commented on task/在庫管理アプリの概要.md
> +
追加しました

2024-08-16 09:09 UTC, yohskeey commented on task/在庫管理アプリの概要.md
追加しました

2024-08-16 09:11 UTC, yohskeey commented on task/在庫管理アプリの概要.md
> +```
シーケンスに記載するアクションの文言を「各種ボタン押下」に変更しました。

> アプリオブジェクトの「入力在庫」へ追加手続きは、入力された値をオンメモリに持っているDataTableに書き込むことを指していますか？

そうです。このドキュメント内で

> この画面は見えない所に入力途中の在庫データ（以下『入力在庫』）を持っています。

と定義されているため、そのように記述しています。

2024-08-16 09:28 UTC, itou commented on task/在庫管理アプリの概要.md
> +```
`入力在庫`という言葉に定義があるのですね。それならばOKと思います。

2024-08-16 09:29 UTC, itou approved these changes

2024-08-19 04:28 UTC, tdc-takase approved these changes

2024-08-19 07:22 UTC, TDC-ohshima commented
「テーブルレイアウト」が、データベースに関する説明の題名としては分かりにくいと思いました。
「データベース」とするのが良いでしょうか？

2024-08-20 05:55 UTC, merged